### ISSUE TITLE
support forum for students? 

### ISSUE THREAD

**Issue by on1arf** [777arc/PySDR#16]
Hi,

More a question then a "issue".

Is there a student forum for pysdr?

I am learning about SDR using the pysdr website as a reference.

It would be interesting if there would be a forum so students can ask questions and talk about SDR, without the need to contact the author directly, or use github (which I think is not surely not the place for that).

I propose a room on matrix as that is an open-source / open-standard conference system.

Thx :-)

**Comment by 777arc** [comment]
Well there's a channel on the IQEngine Discord for those types of questions - https://discord.gg/k7C8kp3b76 alternatively GNU Radios Matrix server has a general chat that gets a lot of random DSP questions.

**Comment by on1arf** [comment]
I had the impression that the GR matrix-room where about GNU Radio, not for SDR/DSP in general.
But if you say that it is OK to use that room, that is OK for me.

Feel free to close this ticket. :+1:

**Comment by 777arc** [comment]
Oh plenty of general SDR/DSP questions in that chat.  Same as how gnuradio conference each year is really just a general software radio style conference with plenty of non GR talks and workshops
