### ISSUE TITLE
Avoid recommending global installs of python packages

### ISSUE THREAD

**Issue by ghykk** [777arc/PySDR#46]
One example would be https://pysdr.org/content/iq_files.html#sigmf-and-annotating-iq-files, `sudo pip install .` is used. Recent changes in Debian (not sure about Ubuntu) strongly discourages this practice due to potential clashes with Python packages managed by the system, and has in fact put in place measures to prevent the installation from proceeding. While there are ways to workaround this, it may still result in dependency hell having these packages installed globally. My understanding is that virtualenv should be preferred (not covered by PySDR) or at least the packages should be installed in user mode with `pip install --user .`.

Also, the sigmf package is available on pypi, so there is no need to compile them from source unless the latest version is needed. Should the guide be updated to use the pypi package (and also reflect the organisation change for sigmf)?

**Comment by 777arc** [comment]
Ah very good point, so maybe to keep things simple we use just `pip install` and then they can figure out based on their own situation if sudo or --user is appropriate?

**Comment by 777arc** [comment]
oh awesome ty!!
